<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>

<h3 style="text-align: center;"><b>Физтех-Школа Прикладной математики и информатики (ФПМИ) МФТИ</b></h3>


---

## Домашнее задание 2: библиотека Numpy и линейная алгебра


Импортируем библиотеки:

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from scipy import ndimage  # спецификатор для работы с изображениями
from scipy import misc
import scipy.stats as sps

from PIL import Image

%matplotlib inline

*Вопросы для самопроверки:*
1. Что такое NumPy?
2. Зачем используется и почему работает быстрее?
3. Что такое линейная алгебра?
4. Как она связана с машинным обучением и глубоким обучением?

### Задание 1

В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета numpy и с ним.

In [2]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j), здесь i -- число строк,
# j -- число столбцов.
a = np.random.sample((10,10))
b = np.random.sample((10,10))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
# тут можно писать код 
# ========
print(a)
print(b)

[[0.92083047 0.03349494 0.45484215 0.02516955 0.72527524 0.57373494
  0.59853592 0.78028086 0.22411045 0.042796  ]
 [0.47486043 0.31563626 0.82513248 0.39167084 0.5732662  0.79297187
  0.83491398 0.21065711 0.41057652 0.70845428]
 [0.95410608 0.19571249 0.44600115 0.79306287 0.86666619 0.27465681
  0.57345977 0.73045273 0.49221365 0.82161274]
 [0.11981615 0.22266524 0.62287648 0.61528987 0.27428729 0.81738175
  0.41673376 0.03440259 0.33576882 0.89183468]
 [0.36577972 0.4455093  0.04467735 0.76358503 0.33471533 0.59919301
  0.11916214 0.52989639 0.9906932  0.76038884]
 [0.51536047 0.55816031 0.62168971 0.89828414 0.63250279 0.12407647
  0.15490293 0.41850369 0.17857035 0.69688233]
 [0.39736287 0.41196069 0.22999517 0.2616129  0.03523328 0.49070099
  0.95234645 0.94427816 0.35869145 0.52713498]
 [0.94796078 0.9327793  0.79496996 0.82795929 0.32133521 0.34221143
  0.41807976 0.21690084 0.8266936  0.0950201 ]
 [0.99347202 0.01479994 0.38663817 0.57967013 0.86241188 0.27049811
  0.38082859

In [3]:
def mult(a, b):
    result = []
    for i in range(0, a.shape[0]):
        resultRow = []
        row = a[i]
        
        for j in range(0, b.shape[1]):
            column = b[:, j]
            resultRow.append(sum([row[k] * column[k] for k in range(0, a.shape[1])]))
        result.append(resultRow)
            
    return np.array(result)
mult(a, b)

array([[3.11372983, 2.20764863, 2.47103793, 2.85396784, 2.20840491,
        2.32756163, 3.16285421, 1.53677468, 3.06807379, 2.25549718],
       [3.12536853, 3.38026841, 2.53147644, 3.11411975, 2.48657368,
        2.92552489, 3.84485281, 2.00485481, 3.53234796, 2.62357783],
       [3.28338489, 2.98900263, 2.94413146, 3.8202601 , 3.30086995,
        3.16754655, 4.15350496, 2.42868433, 4.14605581, 2.53684156],
       [2.02225987, 2.62456252, 1.56826171, 2.21316162, 1.8532099 ,
        1.97162236, 3.0279678 , 1.64648679, 2.49547666, 2.01317853],
       [2.154137  , 2.16349926, 1.92060406, 2.789153  , 2.28880259,
        2.15844828, 2.98132559, 2.52525053, 2.69092501, 2.13669112],
       [2.25415372, 2.51550497, 1.72571788, 2.62897644, 2.37504905,
        2.25325932, 3.12334503, 1.94699715, 2.99871058, 1.7450356 ],
       [2.65976785, 2.66654508, 2.26924143, 2.97099496, 2.39853245,
        2.47297562, 3.33188523, 1.96673335, 3.03086141, 2.76162301],
       [3.01412717, 3.28146142, 2.3851733

In [4]:
def np_mult(a, b):
    return a.dot(b)

np_mult(a, b)

array([[3.11372983, 2.20764863, 2.47103793, 2.85396784, 2.20840491,
        2.32756163, 3.16285421, 1.53677468, 3.06807379, 2.25549718],
       [3.12536853, 3.38026841, 2.53147644, 3.11411975, 2.48657368,
        2.92552489, 3.84485281, 2.00485481, 3.53234796, 2.62357783],
       [3.28338489, 2.98900263, 2.94413146, 3.8202601 , 3.30086995,
        3.16754655, 4.15350496, 2.42868433, 4.14605581, 2.53684156],
       [2.02225987, 2.62456252, 1.56826171, 2.21316162, 1.8532099 ,
        1.97162236, 3.0279678 , 1.64648679, 2.49547666, 2.01317853],
       [2.154137  , 2.16349926, 1.92060406, 2.789153  , 2.28880259,
        2.15844828, 2.98132559, 2.52525053, 2.69092501, 2.13669112],
       [2.25415372, 2.51550497, 1.72571788, 2.62897644, 2.37504905,
        2.25325932, 3.12334503, 1.94699715, 2.99871058, 1.7450356 ],
       [2.65976785, 2.66654508, 2.26924143, 2.97099496, 2.39853245,
        2.47297562, 3.33188523, 1.96673335, 3.03086141, 2.76162301],
       [3.01412717, 3.28146142, 2.3851733

In [5]:
%%time
# засечем время работы функции без NumPy
mult(a,b)

Wall time: 0 ns


array([[3.11372983, 2.20764863, 2.47103793, 2.85396784, 2.20840491,
        2.32756163, 3.16285421, 1.53677468, 3.06807379, 2.25549718],
       [3.12536853, 3.38026841, 2.53147644, 3.11411975, 2.48657368,
        2.92552489, 3.84485281, 2.00485481, 3.53234796, 2.62357783],
       [3.28338489, 2.98900263, 2.94413146, 3.8202601 , 3.30086995,
        3.16754655, 4.15350496, 2.42868433, 4.14605581, 2.53684156],
       [2.02225987, 2.62456252, 1.56826171, 2.21316162, 1.8532099 ,
        1.97162236, 3.0279678 , 1.64648679, 2.49547666, 2.01317853],
       [2.154137  , 2.16349926, 1.92060406, 2.789153  , 2.28880259,
        2.15844828, 2.98132559, 2.52525053, 2.69092501, 2.13669112],
       [2.25415372, 2.51550497, 1.72571788, 2.62897644, 2.37504905,
        2.25325932, 3.12334503, 1.94699715, 2.99871058, 1.7450356 ],
       [2.65976785, 2.66654508, 2.26924143, 2.97099496, 2.39853245,
        2.47297562, 3.33188523, 1.96673335, 3.03086141, 2.76162301],
       [3.01412717, 3.28146142, 2.3851733

In [6]:
%%time
# засечем время работы функции с NumPy
np_mult(a,b)

Wall time: 0 ns


array([[3.11372983, 2.20764863, 2.47103793, 2.85396784, 2.20840491,
        2.32756163, 3.16285421, 1.53677468, 3.06807379, 2.25549718],
       [3.12536853, 3.38026841, 2.53147644, 3.11411975, 2.48657368,
        2.92552489, 3.84485281, 2.00485481, 3.53234796, 2.62357783],
       [3.28338489, 2.98900263, 2.94413146, 3.8202601 , 3.30086995,
        3.16754655, 4.15350496, 2.42868433, 4.14605581, 2.53684156],
       [2.02225987, 2.62456252, 1.56826171, 2.21316162, 1.8532099 ,
        1.97162236, 3.0279678 , 1.64648679, 2.49547666, 2.01317853],
       [2.154137  , 2.16349926, 1.92060406, 2.789153  , 2.28880259,
        2.15844828, 2.98132559, 2.52525053, 2.69092501, 2.13669112],
       [2.25415372, 2.51550497, 1.72571788, 2.62897644, 2.37504905,
        2.25325932, 3.12334503, 1.94699715, 2.99871058, 1.7450356 ],
       [2.65976785, 2.66654508, 2.26924143, 2.97099496, 2.39853245,
        2.47297562, 3.33188523, 1.96673335, 3.03086141, 2.76162301],
       [3.01412717, 3.28146142, 2.3851733

### Задание 2

Напишите функцию, которая по данной последовательности $\{A_i\}_{i=1}^n$ строит последовательность $S_n$, где $S_k = \frac{A_1 + ... + A_k}{k}$.
Аналогично -- с помощью библиотеки NumPy и без нее. Сравните скорость, объясните результат.

In [7]:
# функция, решающая задачу с помощью NumPy
def sec_av(A):
    return np.cumsum(A)/np.arange(1, len(A)+1)

In [8]:
# функция без NumPy
def stupid_sec_av(A):
    S = []
    sum = 0
    for i in range(len(A)):
        sum += A[i]
        S.append(sum/(i+1))
    return np.array(S)

# зададим некоторую последовательность и проверим ее на ваших функциях. 
# Первая функция должна работать ~ в 50 раз быстрее
A = sps.uniform.rvs(size=10 ** 7) 

%time S1 = sec_av(A)
%time S2 = stupid_sec_av(A)
#проверим корректность:
np.abs(S1 - S2).sum()

Wall time: 109 ms
Wall time: 5.01 s


0.0

### Задание 3

Пусть задан некоторый массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все четные элементы исходного массива нужно возвести в куб и записать в обратном порядке относительно позиций этих элементов. Массив $X$ при этом должен остаться без изменений. В конце требуется слить массив $X$ с преобразованным $X$ и вывести в обратном порядке.

In [9]:
# функция, решающая задачу с помощью NumPy
def transformation(X, a=1):
    Y = X
    Y[::2] = a
    Y[1::2] = X[1::2][::-1]**3
    return Y

In [10]:
# функция, решающая задачу  без NumPy
def stupid_transformation(X, a=1):
    indices = list(range(len(X)))
    Y = [X[i]**3 if i % 2 > 0 else a for i in indices]
    rev = reversed(Y[1::2])
    for v, idx in zip(rev, indices[1::2]):
        Y[idx] = v
    return Y

In [11]:
X = sps.uniform.rvs(size=10 ** 7) 
# здесь код эффективнее примерно в 20 раз. 
# если Вы вдруг соберетесь печатать массив без np -- лучше сначала посмотрите на его размер
%time S1 = transformation(X)
%time S2 = stupid_transformation(X)
# проверим корректность:
np.abs(S1 - S2).sum()

Wall time: 203 ms
Wall time: 2.91 s


1327544.7807477547

Что вы можете сказать о скорости вычислений в `NumPy`? Ответ обоснуйте.

**Ответ:**

### Задание 4

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве.Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [12]:
a = np.linspace(2, 5, 3)
b = np.linspace(7, 13, 3)
print(a, b)

[2.  3.5 5. ] [ 7. 10. 13.]


In [13]:
def stupid_scalar_product(a,b):
    return sum(map(lambda vs: vs[0]*vs[1], zip(a,b)))
stupid_scalar_product(a,b)

114.0

In [14]:
def numpy_scalar_product(a,b):
    return a.dot(b)
numpy_scalar_product(a,b)

114.0

In [15]:
%time product_1 = stupid_scalar_product(a,b)
%time product_2 = numpy_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

Wall time: 0 ns
Wall time: 0 ns


0.0

### Задание 5*

Нужно написать матричное произведение БЕЗ циклов и БЕЗ символа @, БЕЗ `np.dot` и вообще БЕЗ какой-либо вспомогательной функции из `numpy`, то есть пользуясь только индексированием, взять суммы по нужным осям и поэлементным произведенем (да, это возможно). Рекомендуем гуглить по запросу "NumPy broadcasting"

In [24]:
a = np.array([[1,2,3], [3,4,5], [6,7,8]])
b = np.array([[5,6,7], [7,8,9], [10,11,12]])

print(np.sum(a*b.T, axis=1))
print(np.sum(np.flip(a, axis=0)*b.T, axis=1))
def cool_matrix_product(A, B):
    return []
a.dot(b)

[ 49 105 201]
[159 105  61]


array([[ 49,  55,  61],
       [ 93, 105, 117],
       [159, 180, 201]])

In [0]:
# тут проверьте, что всё правильно перемножается

Ваш код не будет проверяться нами непосредственно, однако это очень и очень полезное упражнение.

## Бонусная часть (в тесте вопросов по ней не будет)

Image = 2-D численный массив
(или 3-D: CT, MRI, 2D + time; 4-D, …)
В текущем задании, image == Numpy array (np.array)

In [0]:
pic = misc.face()  # встроенная в библиотеку функция, которая загружает картинку с енотом

Выведите тип и размеры для переменной pic. Что лежит внутри?

In [0]:
print(#тут ваш код)

Если вы все сделали правильно, что для формы у вас выведется кортеж из трех чисел: (X, Y, 3). Предположите, откуда там 3?

**Ответ:**

С помощью функции ниже можно вывести изображение и посмотреть, что находится внутри:

In [0]:
plt.imshow(pic)

Убедитесь, что внутри массива `pic` действительно лежат числа. Выведите первые 10 записей.
Массив состоит из троек чисел, которые характеризуют глубину цвета для каждого пикселя. Из пикселей складывается картинка.

In [0]:
print(#тут ваш код)

Выведите значение максимального элемента в матрице. Выведите значение минимального. Выведите среднее по всем элементам матрице. В каких пределах лежат значения глубины цветов?

In [0]:
print(#тут ваш код)

### Задание 2

Теперь загрузим черно-белое изображение енота, чтобы наш массив был не 3-х мерным тензором, а двумерным массивом. Тензоры обрабатываются точно также, но для простоты пока что давайте работать с двумерными массивами, т.е. матрицами.

In [0]:
pic = misc.face(gray=True)

In [0]:
plt.imshow(#тут ваш код)

Выведите форму (shape) полученной картинки `pic`. Какие выводы можно сделать? Положите в `h`,`w` высоту и ширину картинки.

In [0]:
print(#тут ваш код)
h,w=#тут ваш код

Используя библиотеку `numpy`, отразите изображение по горизонтали. Выведите картинку.

Подсказка: не забывайте, что изображения -- это просто двумерные массивы

In [0]:
#тут ваш код

Теперь давайте повысим контрастность -- для этого к каждому пикселю прибавим 50 единиц

In [0]:
#тут ваш код

In [0]:
plt.imshow(pic)

Теперь давайте попробуем превратить наше одноканальное изображение в трехканальный (RGB) тензор. Для этого вместо каждого пикселя в одноканальном изображении (в двумерном массиве) поставим кортеж из трех элементов -- глубины красного, зеленого и голубого соотвественно. Восстановить по ч/б картинке цветной мы не можем, так как мы не можем взять утерянную информацию из ниоткуда, но можем усилить черные и белые участки. Для этого давайте заполним все три канала одинаковыми значениями, деленными на что-то очень большое. Например $--$ на $200$.  То есть, например, если в пикселе `pic[i][j]` лежало значение **200**, то для нового изображения `new_pic` мы заполняем `new_pic[i][j]` кортежем из трех чисел `int(pic[i][j]/3)`. Функция `int` $--$ округление до целой части.

In [0]:
new_pic = np.zeros((h,w,3)) #создадим пустую матрицу, куда будем записывать значения
for i in range(h):
    for j in range(w):
     #тут ваш код

In [0]:
plt.imshow(#тут ваш код)

### Задание 3

Теперь давайте уменьшим качество картинки в 16 раз, путем уменьшения качества изображения, т.е. теперь 16 пикселей по близости надо заполнить одним значением.

In [0]:
from sklearn.datasets import load_sample_image #импорт загрузчика изображения

In [0]:
china = load_sample_image('china.jpg')
plt.imshow(china)

Запишите в переменные `h`, `w`, `c` высоту, ширину, количество каналов соответственно для картинки `china`.

In [0]:
h, w, c = #тут ваш код

Теперь давайте непосредственно перейдем к изменению картинки $--$ мы предлагаем разбивать картинки на квадраты 4 на 4 и заполнять все 16 значений внутри квадрата левым верхним значением. Вы можете сделать иначе.

In [0]:
from copy import copy
compressed_pic = copy(china)
#тут ваш код     

Напишите функцию, которая считает несоотвествие между исходной и сжатой картинкой. Запустите ваш код для `compressed_pic`, `china`

In [0]:
def calculate_mismatch(a,b):
    mismatch=0
    #тут ваш код
    print(mismatch)

In [0]:
calculate_mismatch(#тут ваш код)

Посчитайте синус от каждого значения пикселей изображения `china` по всем каналам. Выведите картинку. Используйте функцию `np.sin` 

In [0]:
#тут ваш код

In [0]:
plt.imshow(#тут ваш код) 

Посмотрите на полученный результат. Как вы думаете, что можно делать с помощью такого преобразования? Какого рода объекты можно распознать?

### Задание 4*

Теперь давайте поработаем с аудиофайлами. Стандартный аудиофайл представляет собой обычный набор чисел, в котором хранятся значения частот, снятых с определенной периодичностью. Итак, самая простая аудиодорожка $-$ одномерный массив.

Первое, что нужно сделать $--$ установить библиотеку для работы с аудио. Она называется `librosa`. Гайд по установке: https://librosa.github.io/librosa/install.html


In [0]:
import librosa #импортируем библиотеку
import IPython.display

In [0]:
audio, sr= librosa.load('Test.wav')  
# записываем наш массив звуковых частот в файл аудио, sr -- число точек, записываемых в секунду. 
# чтобы файл открылся, он должен лежать в той же папке, что и файл HW_2.ipynb

Нашу дорожку можно воспроизвести в самом файле `.ipynb`:

In [0]:
IPython.display.Audio(audio, rate=sr)

Выведите тип данных переменной `audio`, найдите ее длительность и среднее.

In [0]:
print(#тут ваш код)

    Давайте посмотрим, как выглядит наша дорожка. Для этого используем библиотеку `matplotlib.pyplot`

In [0]:
plt.figure(figsize=(25,5))
plt.title('Test.wav')
plt.plot(audio)

Обрежьте последние 4 секунды файла

In [0]:
audio = #тут ваш код

Давайте уменьшим амплитуду на 25%. Что при этом изменится? Напоминаю, что вы всегда можете послушать изменения при помощи `IPython.display.Audio`

In [0]:
audio = #тут ваш код

А еще аудиодорожку можно ускорить. Для этого попробуйте потюнить параметр `rate`

In [0]:
IPython.display.Audio(audio, rate=sr)